### ISSUE TITLE
Plugins Atom

### ISSUE THREAD

**Issue by VictorRomano** [opensanca/trilha-javascript#8]
@RenanJPaula quais plugins do Atom você usa no desenvolvimento de JavaScript no seu dia a dia?

**Comment by RenanJPaula** [comment]
Estou usando estes aqui:

https://atom.io/packages/atom-runner
https://atom.io/packages/editorconfig
https://atom.io/packages/linter
https://atom.io/packages/linter-js-standard
https://atom.io/packages/standard-formatter

**Comment by fczuardi** [comment]
hehe "standard"…

alguns outros:

https://atom.io/packages/linter-eslint
https://atom.io/packages/pretty-json

**Comment by marceltn** [comment]
não é de javascript mas acho mão na roda:

https://atom.io/packages/advanced-open-file
